- name: apt-get install packages
  apt:
    pkg:
      - chrony
      - screen
      - tree
      - nftables
      - iftop
      - zsh
      - tcpdump
      - netsniff-ng
      - net-tools
      - mtr
      - sudo
      - emacs
      - netcat
      - socat
      - htop
      - dnsutils
      - curl
      - parallel
      - jq
      - python3-pip
      - git
      - nmap
      - docker-compose
      - cockpit
      - cockpit-podman
      - ima-evm-utils
      - build-essential 
      - linux-source 
      - bc 
      - kmod 
      - cpio 
      - flex 
      - libncurses5-dev 
      - libelf-dev 
      - libssl-dev 
      - dwarves 
      - bison
      - cockpit-storaged
      - cockpit-system
      - cockpit-machines
      - cockpit-pcp
      - systemd-boot

- name: remove resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: symlink resolv.conf
  ansible.builtin.file:
    src: /usr/lib/systemd/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
